### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by Lowitle** [3cky/telegram-uploader-bot#5]
Hello,

I'm trying to use the docker image.

I set up the docker image, I configured the config.cfg and tried to upload a file. The moment I drop the file inside the folder the container starts to use the network so I think it is trying to upload the file, but it doesn't finish it. Keeps "uploading" after droping the file into the watch folder.

My config.cfg:

```
telegram:
  token: "80******************************************************tY"
  
uploads:
  - directory: "/path/to/watch/dir"
    files:
      - "*.mkv" # file name match by the mask is case insensitive
    document: true # set to true to upload files as documents (without reencoding)
    min_size: 0 # min file size limit to upload (default is 0 - no limit)
    max_size: 2000 MB # max file size limit to upload (default is 50 MB)
    chat: -46******57 # should this be negative?
#    tags:
#      plain:
#        - "work"
#        - "important"
#      regexp:
#        - ".*/(?P<name>.*)\\.jpg" # matched groups will be used as tags prefixed by group names
#      expr:
#        - "(file.Size() > 1024 * 1024) ? 'big' : ''" # tag files bigger than 1 megabyte
```

I have the las parts because # because I don't want any tag, not sure if this causes the problem.
